[package]
name = "virtio-driver"
version = "0.1.0"
authors = ["Kevin Wolf <kwolf@redhat.com>"]
edition = "2018"

[features]
default = []
unsafe-op-in-unsafe-fn = []
vhost-user = ["memfd", "memmap", "vhost"]
vhost-vdpa = ["vhost", "virtio-bindings"]

[dependencies]
bitflags = "1.3"
libc = "0.2.87"
memfd = { version = "0.4.1", optional = true }
memmap = { version = "0.7.0", optional = true }
vhost = { version = "0.4.0", features = ["vhost-user-master", "vhost-vdpa"], optional = true }
vm-memory = { version = "0.8.0", features = ["backend-mmap"] }
vmm-sys-util = "0.9.0"
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"], optional = true }
