[package]
name = "virtio-driver"
version = "0.1.0"
authors = ["Kevin Wolf <kwolf@redhat.com>"]
edition = "2018"
license = "LGPL-2.1-or-later"
description = "virtio driver development library"
keywords = ["virtio", "driver", "user-space"]
categories = ["hardware-support", "virtualization"]

[features]
default = []
vhost-user = ["memfd", "memmap"]
vhost-vdpa = ["virtio-bindings"]
_unsafe-op-in-unsafe-fn = []

[dependencies]
bitflags = "1.3"
libc = "0.2.87"
nix = "0.24.1"
memfd = { version = "0.4.1", optional = true }
memmap = { version = "0.7.0", optional = true }
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"], optional = true }
