[package]
name = "virtio-driver"
version = "0.3.0"
authors = ["Kevin Wolf <kwolf@redhat.com>"]
edition = "2018"
license = "(MIT OR Apache-2.0) AND BSD-3-Clause"
description = "virtio driver development library"
keywords = ["virtio", "driver", "user-space"]
categories = ["hardware-support", "virtualization"]

[features]
default = []
pci = ["pci-driver"]
vhost-user = ["memfd", "memmap"]
vhost-vdpa = ["memfd", "memmap", "virtio-bindings"]
_unsafe-op-in-unsafe-fn = []

[dependencies]
bitflags = "1.3"
libc = "0.2.87"
nix = "0.24.1"
memfd = { version = "0.4.1", optional = true }
memmap = { version = "0.7.0", optional = true }
pci-driver = { version = "0.1.2", default-features = false, optional = true }
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"], optional = true }
