[package]
name = "virtio-driver"
version = "0.1.0"
authors = ["Kevin Wolf <kwolf@redhat.com>"]
edition = "2018"

[features]
default = ["unsafe-op-in-unsafe-fn"]
unsafe-op-in-unsafe-fn = []

[dependencies]
bitflags = "1.3"
libc = "0.2.87"
memfd = "0.4.1"
memmap = "0.7.0"
vhost = { version = "0.3.0", features = ["vhost-user-master"] }
vm-memory = { version = "0.7.0", features = ["backend-mmap"] }
vmm-sys-util = "0.9.0"
