name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-stable:
    name: Check on stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true
            components: rustfmt, clippy

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features=all_transports

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=all_transports

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --features=all_transports -- -D warnings

  check-nightly:
    name: Check on nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            override: true
            components: rustfmt, clippy

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features=all_transports

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=all_transports

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --features=all_transports -- -D warnings

  check-none:
    name: Check using x86_64-unknown-none
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install x86_64-unknown-none stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-none
            profile: minimal
            override: true
            components: clippy

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-none --no-default-features --features=alloc

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target x86_64-unknown-none --no-default-features --features=alloc -- -D warnings
